spring:
  application:
    instance: ${random.uuid}
  output:
    ansi:
      enabled: never
  main:
    banner-mode: "off"

logging:
  pattern:
    console: "[%date{ISO8601}] [%r] [%clr(%level)] [%thread] [%logger] [%F:%L] [${PID:- }] [${spring.zipkin.service.name:${spring.application.name:-}}] [${spring.application.instance:-}] [%X] --- %msg%n"
    file: ${logging.pattern.console}
  level:
    root: INFO
  file: ${spring.application.name}.log.jsonl

#file:
#  max-history: 3
#  max-size: 50MB
