spring:
  application:
    instance: ${random.uuid}
  output:
    ansi:
      enabled: never
  main:
    banner-mode: "off"

logging:
  pattern:
    console: "[%date{ISO8601}] [%r] [%clr(%level)] [%thread] [%logger] [%F:%L] [${PID:- }] [${spring.zipkin.service.name:${spring.application.name:-}}] [${spring.application.instance:-}] [%X] --- %msg%n"
    file: ${logging.pattern.console}
  level:
    root: INFO
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN
    "org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker": WARN
  file:
    max-history: 3
    max-size: 100MB

logging.file: ${spring.application.name}.log.jsonl
logging.path: .
