eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 20 # 30 default
    initialInstanceInfoReplicationIntervalSeconds: 20 # 40 default
#    instanceInfoReplicationIntervalSeconds: 30 # 30 default
    instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 20 # 30 default
      lease-expiration-duration-in-seconds: 60 # 90 default
      #    status-page-url-path: /actuator/info
      #    health-check-url-path: /actuator/health
    healthcheck:
      enabled: false # false default

#logging:
#  com:
#    netflix:
#      discovery: DEBUG

#  fetch-registry: true
#  register-with-eureka: true
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
# eureka.instance.metadataMap.zone = zone1
# eureka.client.preferSameZoneEureka = true

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 10000

spring:
  cloud:
    loadbalancer:
      retry: false

#    inetutils:
#      ignoredInterfaces:
#        - docker0
#        - veth.*
#      preferredNetworks:
#        - 192.168
#        - 10.0
#     useOnlySiteLocalInterfaces: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
        loggerLevel: basic
  hystrix:
    enabled: false
