spring:
  profiles: development

  datasource:
    url: jdbc:mysql://192.168.99.100:3306/alicedb?characterEncoding=UTF-8&useSSL=false
    username: alice
    password: alice-secret
    # user/pass can be combined into the url: jdbc:mysql://alice:alice-secret@192.168.99.100:3306/alicedb?characterEncoding=UTF-8&useSSL=false

jpa:
    hibernate:
      ddl-auto: update # create-drop # update, validate, create-drop
    properties:
      hibernate:
        dialect: ai.hyacinth.core.service.jpa.hibernate.dialect.MySQLDialect

test:
  key: 456
  key2: 999

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  profiles: production

  jpa:
    hibernate:
      ddl-auto: validate
