spring:
  application:
    name: gateway-server

  session:
    store-type: redis
    timeout: 1800s
  redis:
    url: redis://redis:alice-secret@192.168.99.100:6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
#          trustedX509Certificates:
#          - cert1.pem
#          - cert2.pem

server:
  port: 9090
  ssl:
    enabled: false
    key-alias: tomcat
    key-store-password: password
    key-store: ./tomcat.ks # or classpath:keystore.p12
    # key-store-type: PKCS12
#  http2:
#    enabled: true

security:
  require-ssl: ${server.ssl.enabled}

#logging:
#  level:
#    org:
#      springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true

ai.hyacinth.core.service.gateway.server:
  jwt:
    enabled: true
    signing-key: utWVSlUPfb3be0npL0JN41vuKJpFehpVZZKzJz5mWWllpT0X5v6IDFQhn51atRVxsaOqbxK1o2nJdQ2gKsKLPgIxaN0wLYiuWfFBS83zo53+d7VoZrJDMqDN7rpTsdERZjoAaAVQ6iGb3UzWYz0aC1H9SDSJHL/M4FUhU9R3V4g=
#    signing-key-file: file:keys/sym_keyfile.key
    expiration: 2h
    token-version: 1
  security:
    authenticated-required: true
    logout-url: /auth-service/api/logout
  rules:
  - path: /auth-service/api/login
    method: POST
    authority: any
    service: user-service
    uri: /api/authentication/login
    post-processing:
      - authentication-jwt
      - authentication-cookie
      - api
  - path: /user-service/api/users/whoami
    authority: admin, user
    service: user-service
    uri: /api/users/current
  - path: /user-service/api/users/me
    authority: user
    service: user-service
    uri: /api/users/${X-Principle}
    post-processing: api
  - path: /order-service/api/orders
    method: POST
    authority: user
    service: debug-service
    uri: /api/orders
    request-body:
      userId: ${X-Principle}
      otherId: 123
    request-param:
      test: ${X-Principle}
  - path: /order-service/api/{*call}
    authority: admin, api
    service: order-service
    uri: "/api{call}"
  - path: /debug-service/{*call}
    authority: any
    service: debug-service
    uri: "{call}"
  - path: /ping
    authority: any
    uri: /api/ping
  - path: /actuator/{*call}
    authority: any
    uri: "{call}"

#zuul:
#  host:
#    maxTotalConnections: 200
#    maxPerRouteConnections: 30
#
#  ignoredServices: '*'
#
#  prefix: /api
#  stripPrefix: false
#
#  routes:
#    user-service:
#      path: /user-service/**
#      serviceId: user-service
