spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    ai:
      hyacinth:
        core:
          service:
            examples:
              debug:
                web: DEBUG
